server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: compras
    password: compras
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        # format_sql: true version legible pero con warning amarillo
        "[format_sql]": true

jwt:
  secret: MiSecretSuperSeguroJWTDeMasDe32Caracteres!!
  expiration: 3600000  # 1 hora en ms
